spring:
  datasource:
    url: jdbc:h2:mem:test # memory 모드로 동작. 외부 DB 붙지 않음.
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

---
spring:
  profiles: mysql-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/training
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          default_batch_fetch_size: 100
          format_sql: true
          #        generate_statistics: true
          jdbc:
            batch_size: 1000
          order_inserts: true